"""Pydantic models for structured planning, dependency graphs, and execution state."""

from datetime import datetime, timezone
from enum import Enum
import uuid
from typing import Any
from pydantic import BaseModel, ConfigDict, Field


class PlanStatus(str, Enum):
    """Overall state of a multi-step execution plan."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class StepStatus(str, Enum):
    """Execution state of an individual plan step."""

    PENDING = "pending"
    RUNNING = "running"
    VERIFYING = "verifying"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"
    RECOVERING = "recovering"


class FailureClassification(str, Enum):
    """Structured categorization of action or verification failures."""

    WINDOW_NOT_FOUND = "window_not_found"
    ELEMENT_NOT_FOUND = "element_not_found"
    VERIFICATION_FAILED = "verification_failed"
    TIMEOUT = "timeout"
    POLICY_BLOCKED = "policy_blocked"
    DEVICE_UNAVAILABLE = "device_unavailable"
    TOOL_ERROR = "tool_error"
    UNKNOWN = "unknown"


class PlanStep(BaseModel):
    """An individual structured action step within a plan."""

    model_config = ConfigDict(extra="forbid")

    step_id: str = Field(default_factory=lambda: f"step_{uuid.uuid4().hex[:8]}")
    name: str = Field(..., min_length=1)
    tool: str = Field(..., min_length=1)
    arguments: dict[str, Any] = Field(default_factory=dict)
    depends_on: list[str] = Field(default_factory=list, description="IDs of steps that must complete first")
    verification_required: bool = True
    status: StepStatus = StepStatus.PENDING
    retry_count: int = 0
    max_retries: int = Field(default=2, ge=0, le=5)
    result: Any | None = None
    error: str | None = None


class Plan(BaseModel):
    """A structured multi-step execution plan generated by the Autonomous Planner."""

    model_config = ConfigDict(extra="forbid")

    plan_id: str = Field(default_factory=lambda: f"plan_{uuid.uuid4().hex[:8]}")
    goal: str = Field(..., min_length=1)
    steps: list[PlanStep] = Field(default_factory=list)
    status: PlanStatus = PlanStatus.PENDING
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    timeout_seconds: float = Field(default=120.0, ge=1.0, le=3600.0)
    device_id: str | None = None
    recovery_strategy: str = "reobserve_and_retry"
    current_step_index: int = 0
    final_response: str | None = None
